## Numpy 矩阵

* mat 函数 (将数组转换成矩阵)
* I 属性: 矩阵求逆运算
* T 属性: 矩阵"转置"
* eye(n): 创建 n * n 的单位(对角)矩阵

In [1]:
import numpy as np

In [3]:
np.random.rand(4,4)

array([[0.57486522, 0.84712587, 0.8877264 , 0.30747157],
       [0.23072121, 0.42057232, 0.18089633, 0.47296725],
       [0.54067182, 0.96651208, 0.11704529, 0.27078143],
       [0.33898313, 0.76155354, 0.31972605, 0.4480029 ]])

In [7]:
randMat = np.mat(np.random.rand(4,4))
print(randMat)
print type(randMat)

[[0.61711929 0.12566212 0.89550619 0.033981  ]
 [0.42390697 0.67349679 0.59741568 0.54741123]
 [0.3843519  0.19956617 0.16884512 0.37398733]
 [0.46323716 0.57384279 0.69539504 0.76076181]]
<class 'numpy.matrixlib.defmatrix.matrix'>


In [8]:
print randMat.I

[[ 0.61009068  0.88925649  3.54713193 -2.41087667]
 [-0.50799843  3.92607603 -0.33612316 -2.63710665]
 [ 0.79466038 -1.06785711 -2.40846548  1.91688015]
 [-0.7146893  -2.52681527  0.29516923  3.01947777]]


In [9]:
print randMat.T

[[0.61711929 0.42390697 0.3843519  0.46323716]
 [0.12566212 0.67349679 0.19956617 0.57384279]
 [0.89550619 0.59741568 0.16884512 0.69539504]
 [0.033981   0.54741123 0.37398733 0.76076181]]


In [10]:
print np.eye(4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
randMat * randMat.I

matrix([[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00,  1.00000000e+00, -2.22044605e-16,
         -4.44089210e-16],
        [-2.77555756e-17,  2.22044605e-16,  1.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00]])